security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            form_login:
                login_path: user_login
                check_path: user_login
                username_parameter: username
                password_parameter: password
                enable_csrf: true
                csrf_parameter: _token
                default_target_path: homepage
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
            logout:
                path: user_logout
                target: homepage
            entry_point: 'form_login'


    access_control:
        - { path: ^/user/(login|register), roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_SUPER_MODERATOR: ROLE_MODERATOR
        ROLE_ADMIN: ROLE_SUPER_MODERATOR


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
