twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_version: '%app_version%'
    form_themes: ['shared/form/btn_submit.html.twig']

when@test:
    twig:
        strict_variables: true
