parameters:
    app_locale: 'fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\EventListener\UserConnexionListener:
        tags:
            - name: kernel.event_subscriber
              dispatcher: security.event_dispatcher.main